### ISSUE TITLE
About “config.yml”

### ISSUE THREAD

**Issue by AaronHzy** [Beelzebu/Coins#6]
Can not set "Config.yml" to UTF-8
Symbols lead to garbled characters

**Comment by Beelzebu** [comment]
did you tried setting the character set to utf8 in the text editor in which you're reading the file?

**Comment by AaronHzy** [comment]
yes,but restore defaults after restart

**Comment by AaronHzy** [comment]
Yes
When I shut down the server modify “config.yml” and start server, no problem
but restart the server again(Not modify “config.yml”)，An error occurred and "config.yml" restore defaults

`[22:57:59 INFO]: [Coins] Enabling Coins v2.2.2
[22:57:59 ERROR]: Cannot load plugins\Coins\config.yml
[22:58:00 ERROR]: Cannot load plugins\Coins\config.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xDB4E) special characters are not allowed
in "'string'", position 477
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:167) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.nifheim.beelzebu.coins.bukkit.utils.Configuration.reload(Configuration.java:113) [%5B经济%5D%5B货币%5DCoins-2.2.2.jar:?]
        at net.nifheim.beelzebu.coins.core.utils.FileManager.updateFiles(FileManager.java:364) [%5B经济%5D%5B货币%5DCoins-2.2.2.jar:?]
        at net.nifheim.beelzebu.coins.core.Core.start(Core.java:80) [%5B经济%5D%5B货币%5DCoins-2.2.2.jar:?]
        at net.nifheim.beelzebu.coins.bukkit.Main.onEnable(Main.java:60) [%5B经济%5D%5B货币%5DCoins-2.2.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
        at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:67) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
        ... 19 more
[22:58:00 INFO]: [Coins] The config file is up to date.`

**Comment by Beelzebu** [comment]
Seems that is a problem with windows that can't read the files in utf8, try replacing the simple quotes `'string'` to double quotes `"string"` for example `Prefix: '&c&lCoins &6&l>&7'` would be `Prefix: "&c&lCoins &6&l>&7"`

**Comment by AaronHzy** [comment]
no，Useless :(

**Comment by Beelzebu** [comment]
Try adding `-Dfile.encoding=UTF-8` to the startup parameters.
>-Dfile.encoding=UTF-8
Position: before "-jar"
This parameter will ensure that all UTF-8 characters are being saved properly in server's log files, all characters should be correctly displayed in the console as well. Put this parameter before "-jar"
This parameter is only useful for older Linux based distributions, this may cause weird characters on Windows operating system.

https://www.spigotmc.org/wiki/start-up-parameters/
